### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'INJECT'

### ISSUE THREAD

**Issue by grxxnzzz** [serpotapov/Kohya_ss-GUI-LoRA-Portable#2]
Здравствуйте, подскажите, пожалуйста, что я мог не так сделать? Папки Sample у меня нет, настройки брал из видео, пересмотрел несколько раз и всё совпадает.

При нажатии **Train Model** в консоли выдает это:
```
Traceback (most recent call last):
  File "C:\LoRA\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\LoRA\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "C:\LoRA\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\LoRA\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\LoRA\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\LoRA\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\LoRA\dreambooth_gui.py", line 336, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'INJECT'
```

Всё, я кажется понял, в чем дело...
А нет, всё так же.

**Comment by grxxnzzz** [comment]
Переустановил и всё заработало. Прошу прощения, что натыкал тут, я просто гитом мало пользуюсь.
Спасибо за проделанную работу.

**Comment by igorpichnenko** [comment]
Посмотрел видел до конца, сделал все по инструкции, а так же пробовал конфиг к видео, но после нажатия на Train model у меня ругается так, устанавливал в корень диска E. пробовал все переустановить но не помогло.

Loading config...
Folder 100_annapichnenko: 17 images found
Folder 100_annapichnenko: 1700 steps
Traceback (most recent call last):
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Kohya_ss-GUI-LoRA-Portable-main\lora_gui.py", line 422, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'steam'

Что может не так быть?

**Comment by igorpichnenko** [comment]
это у меня на 422 строке, я не силен в python что бы править, что тут нужно сделать?

  # Loop through each subfolder and extract the number of repeats
    for folder in subfolders:
        # Extract the number of repeats from the folder name
        repeats = int(folder.split('_')[0])

        # Count the number of images in the folder
        num_images = len(
            [
                f
                for f, lower_f in (
                    (file, file.lower())
                    for file in os.listdir(
                        os.path.join(train_data_dir, folder)
                    )
                )
                if lower_f.endswith(('.jpg', '.jpeg', '.png', '.webp'))
            ]
        )
