### ISSUE TITLE
Ошибка при тренировке

### ISSUE THREAD

**Issue by Ferallus** [serpotapov/Kohya_ss-GUI-LoRA-Portable#20]
Geforce 3060ti.

bin C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Kohya_ss-GUI-LoRA-Portable-main/venv/Lib/site-packages/cv2/../../x64/vc14/bin')}
  warn(msg)
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: C:\Kohya_ss-GUI-LoRA-Portable-main\venv\Lib\site-packages\cv2\../../x64/vc14/bin;C:\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts;git\cmd;python did not contain ['cudart64_110.dll', 'cudart64_120.dll'] as expected! Searching further paths...
  warn(msg)
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/DESKTOP-NCBTFOS')}
  warn(msg)
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('home = C:/Kohya_ss-GUI-LoRA-Portable-main/python')}
  warn(msg)
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('_ENV=C:/Kohya_ss-GUI-LoRA-Portable-main/venv')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
ERROR: libcudart.so could not be read from path: None!
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version None
CUDA SETUP: Loading binary C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1700
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1700
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1700
steps:   0%|                                                                                  | 0/1700 [00:00<?, ?it/s]epoch 1/1
C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\xformers\ops\fmha\flash.py:338: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  and inp.query.storage().data_ptr() == inp.key.storage().data_ptr()
Traceback (most recent call last):
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 773, in <module>
    train(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 629, in train
    optimizer.step()
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 370, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 290, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\optim\optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 263, in step
    self.update_step(group, p, gindex, pindex)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 504, in update_step
    F.optimizer_update_8bit_blockwise(
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\functional.py", line 981, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                                  | 0/1700 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Kohya_ss-GUI-LoRA-Portable-main\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/SD/Deliberate_v2.safetensors', '--train_data_dir=C:/LoRa', '--resolution=512,512', '--output_dir=C:/LoRa', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Oscar', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=170', '--train_batch_size=1', '--max_train_steps=1700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by serpotapov** [comment]
Приветствую 🖐
Перекачайте сборку, всё заработает 👏

**Comment by Ferallus** [comment]
Благодарю, заработало
